#Scopa Rules
print('\n'
'How to Play Scopa','\n'
'A game of Scopa is traditionally played using a deck of Napoletane cards.','\n'
'The Italian deck is composed of only 40 cards.' ,'\n'
'The deck is composed of four suits, which includes: Spades, Coins, Cups, Clubs.','\n'
'Each suit has 7 symbol cards and 3 face cards, which include Knave, Knight, and King.','\n'
'Each card has a numerical value in the game, which is represented by the number of symbols on the card','\n'
'(e.g. 4 swords is equivalent to 4). The face cards have numerical values as well:','\n'
'Fante is equivalent to 8, Cavallo is equivalent to 9, and Re is equivalent to 10.','\n'
'During a round of Scopa, players must gather around in a circle, with teammates seated','\n'
'across each other. One player is designated as the dealer and has to deal 3 cards to each','\n'
'player starting on the one to his right and continuing to deal counter-clockwise.','\n'
'The dealer must also place four cards facing up on the surface.','\n'
'The player can either place a card on the table along with the four other table cards or','\n'
'try to capture other cards by playing a card that matches the numerical value of one or','\n'
'more cards on the table. The captured cards are then placed face down on a pile on the','\n'
'player’s side so the total value of the cards can be added later to determine the winner.','\n'
'A Scopa or “sweep” is achieved when one player manages to capture all the table cards on one turn.','\n'
'\n'
'Once all the players have used the three cards, the dealer has to distribute new cards to','\n'
'each player starting with the person to his right. In this round, no more table cards are dealt','\n'
'and the player to the dealer’s right must begin the round again. This is done repeatedly ','\n'
'until there are no more cards left to deal in the deck. Once the dealer has played his last','\n'
'card, the player who was able to perform the last capture is given the privilege of taking','\n'
'all the cards left on the table. Points are then calculated for each player or team and whoever','\n'
'scores the most wins the game. In the event that there is no winner, the player to the right of','\n'
'the dealer must reshuffle the cards and assume the role of dealer on the next round.','\n'
'\n')
