#Scopa Rules
print('\n'
'How to Play Scopa','\n'
'A game of Scopa is traditionally played using a deck of Napoletane cards.','\n'
'The Italian deck is composed of only 40 cards.' ,'\n'
'The deck is composed of four suits, which includes: Spades, Coins, Cups, Clubs.','\n'
'Each suit has 7 symbol cards and 3 face cards, which include Knave, Knight, and King.','\n'
'Each card has a numerical value in the game, which is represented by the number of symbols on','\n'
'the card (e.g. 4 swords is equivalent to 4). The face cards have numerical values as well:','\n'
'Knave is equivalent to 8, Knight is equivalent to 9, and King is equivalent to 10.','\n'
'Due to the simplification of the game the three face cards have been removed and substituted','\n'
'with their numerical values to make the game more accessible to all new players.','\n'
'\n'
'During a round of Scopa, 3 cards are dealt to each player each turn.','\n'
'Before starting, four cards facing up must be placed on the table.','\n'
'Each turn, the player can either place a card on the table along with the other table cards or','\n'
'try to capture other cards by playing a card that matches the numerical value of one or','\n'
'more cards on the table (e.g. you throw 7 of spades, you can take sums of cards such as 4 of cups and','\n'
'of Coins from the table). The captured cards are then placed face down on a pile on the','\n'
'player’s side so the total value of the cards can be added later to determine the winner.','\n'
'A Scopa or “sweep” is achieved when one player manages to capture all the table cards on one turn.','\n'
'\n'
'Once all the players have used the three cards, the dealer has to distribute 3 new cards to','\n'
'each player. From this round until the end, no more table cards are dealt','\n'
'and the player must play the round again. This is done repeatedly ','\n'
'until there are no more cards left to deal in the deck. Once the last player has played his last','\n'
'card, the player who was able to perform the last capture is given the privilege of taking','\n'
'all the cards left on the table. Points are then calculated for each player and whoever','\n'
'scores the most wins the game. The points system consists of:','\n'
'The player who has the most cards gains a point, the player with most cards of coin suit','\n'
'also gains a point. The seven of coins is a special card and whoever collects it gets a point.','\n'
'Each Scopa or "sweep" that a player has got is a point.','\n'
'When the game is over the player with most poins wins and if 2 players have same points it is' ,'\n'
'therefore a draw. This game has been simplifid to these extents and I made it two player','\n'
'only when originally was up to 4 players including teams of 2 players.' ,'\n'
'Other points sytems have been excluded from the original version but the game is still functioning.','\n'
'Enjoy!','\n')
